[workspace]
members = [
    "demand_generator",
    "data_fetcher",
    "metrics_processor",
    "rewards_calculator",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Malbec Labs <dev@malbeclabs.com>"]
readme = "README.md"
description = "DoubleZero Off-Chain Rewarder"
license = "Apache-2.0"
repository = "https://github.com/doublezerofoundation/doublezero-rewarder"
homepage = "https://github.com/doublezerofoundation/doublezero-rewarder"


[workspace.dependencies]
anyhow = "1"
arrow = { version = "55", features = ["prettyprint"] }
base64 = "0"
borsh = "1"
chrono = { version = "0", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
csv = "1"
duckdb = { version = "1", features = ["bundled"] }
flate2 = "1"
figment = { version = "0", features = ["env", "toml"] }
futures-util = "0"
hex = "0"
humantime = "2"
humantime-serde = "1"
doublezero-serviceability = { git = "ssh://git@github.com/malbeclabs/doublezero", features = [ "no-entrypoint" ] }
doublezero-telemetry = { git = "ssh://git@github.com/malbeclabs/doublezero", features = [ "no-entrypoint" ] }
svm-hash = { version = "0.1.0-beta.1", features = [ "bytemuck" ] }
md5 = "0"
parquet = { version = "55", features = ["arrow", "async"] }
rand = "0"
rust_decimal = { version = "1", features = ["serde", "macros"] }
sha2 = "0"
network-shapley = { git = "https://github.com/doublezerofoundation/network-shapley-rs", features = ["serde"] }
reqwest = { version = "0", features = [ "json" ] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solana-client = "2.2.7"
solana-account-decoder = "2.2.7"
solana-sdk = "2.2.2"
tabled = { version = "0", features = [ "std", "derive" ]}
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0" }
toml = "0"
tracing = "0"
tracing-subscriber = { version = "0", features = ["env-filter"] }
