# Default configuration for DoubleZero Rewarder
# This file contains base settings that apply to all environments
# Environment-specific settings in devnet.toml, testnet.toml, etc. will override these

# General settings
log_level = "info"

# RPC settings
[data_fetcher.rpc]
commitment = "finalized"
timeout_secs = 30
max_retries = 3

# Metrics processor settings
[metrics_processor.metrics]
uptime_threshold = 0.95
percentile_bins = [50, 75, 90, 95, 99]

[demand_generator.ip_info]
api_token = "<ip_info_token>"
