# Default configuration for DoubleZero Rewarder
# This file contains base settings that apply to all environments
# Environment-specific settings in devnet.toml, testnet.toml, etc. will override these

# General settings
log_level = "info"

# RPC settings
[ingestor.rpc]
solana_url = "https://api.mainnet-beta.solana.com"

# Metrics processor settings
[ingestor.metrics]
uptime_threshold = 0.95
percentile_bins = [50, 75, 90, 95, 99]

[calculator]
