# Testnet configuration for DoubleZero Rewarder
[data_fetcher.rpc]
url = "https://doublezerolocalnet.rpcpool.com/f50e62d0-06e7-410e-867e-6873e358ed30"

[data_fetcher.programs]
serviceability_program_id = "DZtnuQ839pSaDMFG5q1ad2V95G82S5EC4RrB3Ndw2Heb"
telemetry_program_id = "3KogTMmVxc5eUHtjZnwm136H5P8tvPwVu4ufbGPvM7p1"
