name: local-validator
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SOLANA_CLI: v2.3.7

jobs:
  test-doublezero-solana-clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Solana toolchain
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/$SOLANA_CLI/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Generate ~/.config/solana/id.json
        run: solana-keygen new --silent --no-bip39-passphrase
      - name: Start Solana mainnet-beta fork in background
        run: cargo run --bin doublezero-solana-fork -- -um > /dev/null 2>&1 &
      - name: Build DoubleZero Solana
        run: cargo build --bin doublezero-solana
      - name: Check starting SOL balance
        run: solana balance -u l
      - name: Run DoubleZero Solana tests
        run: bash sh/test_doublezero_solana_clean.sh
      - name: Check ending SOL balance
        run: solana balance -u l